// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCq5QVjcH9asWfKxH8PqHMnFH4xp6KFQFQ',
//     appId: '1:825931511240:web:7b2badf7e1051aaba9fcfd',
//     messagingSenderId: '825931511240',
//     projectId: 'pet-paw-project',
//     authDomain: 'pet-paw-project.firebaseapp.com',
//     storageBucket: 'pet-paw-project.firebasestorage.app',
//     measurementId: 'G-L9STEGHT8X',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDMp-VLfiIIWxLTU3lCbocoYQTYkatoLQk',
//     appId: '1:825931511240:android:83d56ebd124fbd95a9fcfd',
//     messagingSenderId: '825931511240',
//     projectId: 'pet-paw-project',
//     storageBucket: 'pet-paw-project.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBCKsD283lmiXZ7Dr01HaFjGuJAcR_V98w',
//     appId: '1:825931511240:ios:8ca32ac8c20ad46da9fcfd',
//     messagingSenderId: '825931511240',
//     projectId: 'pet-paw-project',
//     storageBucket: 'pet-paw-project.firebasestorage.app',
//     iosBundleId: 'com.example.petPaw',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBCKsD283lmiXZ7Dr01HaFjGuJAcR_V98w',
//     appId: '1:825931511240:ios:8ca32ac8c20ad46da9fcfd',
//     messagingSenderId: '825931511240',
//     projectId: 'pet-paw-project',
//     storageBucket: 'pet-paw-project.firebasestorage.app',
//     iosBundleId: 'com.example.petPaw',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCq5QVjcH9asWfKxH8PqHMnFH4xp6KFQFQ',
//     appId: '1:825931511240:web:74d5df84e313cfa4a9fcfd',
//     messagingSenderId: '825931511240',
//     projectId: 'pet-paw-project',
//     authDomain: 'pet-paw-project.firebaseapp.com',
//     storageBucket: 'pet-paw-project.firebasestorage.app',
//     measurementId: 'G-SSV1J50KTY',
//   );
// }
